version: "3.8"
services:
  app:
    container_name: "gestion-de-paie-react-native-container"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
